# Generated by Django 3.1.4 on 2020-12-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=30, unique=True, verbose_name='资产编号')),
                ('sn', models.CharField(max_length=50, unique=True, verbose_name='设备SN')),
                ('buy_time', models.DateField(default='2000-01-01', verbose_name='购买时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.assetmodel', verbose_name='设备型号')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='公司')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='cpu型号')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='磁盘容量')),
                ('unit', models.IntegerField(choices=[(1, 'GB'), (2, 'TB'), (3, 'PB')], verbose_name='单位')),
                ('sn', models.CharField(max_length=20, unique=True, verbose_name='磁盘SN')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='InternetAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20, unique=True, verbose_name='主机名')),
                ('ipaddr', models.CharField(max_length=15, unique=True, verbose_name='IP地址')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, unique=True, verbose_name='维保公司')),
                ('person_number', models.CharField(blank=True, max_length=50, verbose_name='联系人及电话')),
            ],
            options={
                'ordering': ('-company_name',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='制造商品牌')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[(1, 'DDR3'), (2, 'DDR4'), (3, 'DDR5')], default=1, max_length=1, verbose_name='内存型号')),
                ('size', models.IntegerField(default=8, verbose_name='内存容量')),
                ('unit', models.IntegerField(default=1, verbose_name='单位')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='网卡名')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_model', models.CharField(max_length=10, verbose_name='raid信息')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True, verbose_name='资源类型')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'ordering': ('-type',),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20, unique=True, verbose_name='主机名')),
                ('server_type', models.CharField(choices=[(1, '物理机'), (2, '虚拟机')], max_length=1, verbose_name='服务器类型')),
                ('os_system', models.CharField(max_length=10, verbose_name='操作系统')),
                ('ipaddr', models.CharField(max_length=15, unique=True, verbose_name='IP地址')),
                ('disk', models.IntegerField(verbose_name='硬盘')),
                ('cpu', models.IntegerField(verbose_name='CPU核数')),
                ('memory', models.IntegerField(verbose_name='内存')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServerAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(max_length=10, unique=True, verbose_name='服务器类型')),
                ('os_system', models.CharField(max_length=10, verbose_name='操作系统')),
                ('manage_ip', models.CharField(max_length=15, unique=True, verbose_name='管理卡IP')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('asset_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.assets', verbose_name='资产ID')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.cpu', verbose_name='CPU')),
                ('disk_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.disk', verbose_name='硬盘')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.memory', verbose_name='内存')),
                ('network_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.networkcard', verbose_name='网卡')),
                ('raid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.raid', verbose_name='Raid信息')),
            ],
        ),
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15, verbose_name='IP地址')),
                ('vip', models.CharField(blank=True, max_length=15, verbose_name='VIP地址')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('network_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.networkcard', verbose_name='网卡绑定')),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcetype', verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='assets',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.manufacturer', verbose_name='设备品牌'),
        ),
        migrations.AddField(
            model_name='assets',
            name='owner',
            field=models.ManyToManyField(related_name='company_owner', to='resources.Company', verbose_name='所属者'),
        ),
        migrations.AddField(
            model_name='assets',
            name='use',
            field=models.ManyToManyField(related_name='company_use', to='resources.Company', verbose_name='使用者'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.manufacturer'),
        ),
    ]
